/* SPDX-License-Identifier: LGPL-2.1-or-later */
/*
 * Copyright (C) 2026 Ideas on Board Oy
 *
 * Base classes and types for LSC algorithms implementations
 */

#include "lsc_base.h"

/**
 * \file lsc_base.h
 * \brief Base types and definitions for LscImplementation class hierarchy
 *
 * Split the common classes and types definitions to a dedicated file to avoid
 * circular inclusions.
 *
 * Both LscGrid and LscPolynomial inherit from LscImplementation and they are
 * instantiated from lsc.h as the LscAlgorithm::init() function is there inlined.
 *
 * For this reason lsc.h needs to include lsc_grid.h and lsc_polynomial.h which
 * need the LscImplementation class definition themselves.
 *
 * Split the LscImplementation interface definition to this file so that it can
 * be included by both lsc_grid.h and lsc_polynomial.h, which are then included
 * by lsc.h.
 */

namespace libcamera {

namespace ipa {

namespace lsc {

/**
 * \class Components
 * \brief Associate a colour components with a list of gains
 * \tparam T The type used to store the gain values when loaded from tuning file
 *
 * Lsc tables are defined as a list of gain values associated to a colour
 * component.
 *
 * As different ISP support different colour components (usually 'r', 'gr',
 * 'gb', 'b' or just 'r', 'g', 'b') this class associates a string
 * identifier for the colour component to a list of gains of type \a T.
 *
 * Each key name shall match an entry in the tuning file and the type \a T
 * shall match the size of the registers where gains are stored.
 *
 * The list of keys is provided to the LscAlgorithm class using \a
 * LscDescriptor::keys.
 */

/**
 * \class ComponentsMap
 * \brief Associate a colour temperature to a lsc table
 * \tparam T The type used to store the gain values when loaded from tuning file
 *
 * An lsc table is generated during the tuning phase for a specific light
 * temperature, and a tuning file usually contains lsc tables generated for
 * several different colour temperatures.
 *
 * This class associates an lsc table to the colour temperature used when the
 * table has been generated.
 */

} /* namespace lsc */

/**
 * \struct LscDescriptor
 * \brief Describe the ISP lsc engine
 *
 * \var LscDescriptor::keys
 * \brief The list of colour components to which a list of gains is associated
 * with in the tuning file. Used for parsing the tuning file
 *
 * \var LscDescriptor::numHCells
 * \brief Number of horizontal cells of the ISP lsc grid. Used for validating
 * the list of gains parsed from tuning file
 *
 * \var LscDescriptor::numVCells
 * \brief Number of vertical cells of the ISP lsc grid. Used for validating
 * the list of gains parsed from tuning file
 *
 * \var LscDescriptor::sensorSize
 * \brief The physical sensor size. This is the largest frame size used to
 * generate the lsc table. Only used by the polynomial lsc algorithm
 */

/**
 * \class LscImplementation
 * \brief Pure virtual base class for lsc algorithm implementations
 * \tparam T The type used to store the gain values when loaded from tuning file
 * \tparam U The fixedpoint format used to convert gain values generated by
 * polynomial expansion to the register format
 *
 * Defines the interface for the lsc algorithm implementation. Currently
 * implemented by LscGrid and LscPolynomial.
 */

/**
 * \fn LscImplementation::~LscImplementation
 * \brief Virtual class destructor
 */

/**
 * \fn LscImplementation::parseLscData
 * \brief Parse \a tuningData using \a descriptor
 * \param[in] tuningData The tuning data
 * \param[in] descriptor The lsc engine descriptor
 *
 * Parse the tuning file using the \a descriptor to identify the colour
 * components in the tuning data and validate the size of the loaded gains
 * tables.
 *
 * \return 0 on success, a negative error number otherwise
 */

/**
 * \fn LscImplementation::resampleLscData
 * \brief Re-sample the lsc components for \a cropRectangle
 * \param[in] cropRectangle The sensor analogue crop rectangle
 * \param[in] xPos List of horizontal positions of the lsc grid nodes
 * \param[in] yPos List of vertical positions of the lsc grid nodes
 *
 * Lsc tables are expressed in two formats:
 * - A list of gain values (LscGrid)
 * - A radial polynomial (LscPolynomial)
 *
 * Grid-based lsc data are generated using an image at a fixed resolution and
 * can't at the moment be re-sampled when a different resolution is used for a
 * streaming session. Re-sampling a grid lsc table will return the same table
 * as loaded from the tuning file.
 *
 * Polynomial are more flexible and can be re-sampled for a given resolution
 * using a list of horizontal and vertical nodes that define the lsc grid.
 * Polynomial lsc tables have to be re-sampled every time a new configuration is
 * applied, as each streaming session might use a different sensor crop
 * rectangle.
 *
 * \a cropRectangle represents the size of the frame on which the polynomial Lsc
 * has to be re-sampled on.
 *
 * \a xPos and \a yPos represent the position of the grid nodes vertexes in
 * the [0, 1] interval. In example an equally spaced grid of 16 nodes will have
 * each segment of size 0.0625 and the list of nodes position will be
 * [0, 0.0625, 0.125, 0.1875, ... , 1]. It is expected that the first position
 * is 0 and the last position is 1.
 */

} /* namespace ipa */

} /* namespace libcamera */
