# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2025, Ideas on Board Oy

import contextlib
import os
import shutil
from pathlib import Path
from sphinx.util import logging

__version__ = "0.0.0"

logger = logging.getLogger(__name__)


def on_config_inited(app, config):
    entries = []

    outdir = Path(app.outdir).absolute()

    for index, items in enumerate(config.doxygen_links):
        err_msg_prefix = f'Config variable `doxygen_links` contains invalid entry {index} (`{items}`)'

        if len(items) != 2:
            raise ValueError(f'{err_msg_prefix}: expected (path, target)')

        path = Path(items[0]).absolute()
        target = Path(items[1]).relative_to(path.parent, walk_up=True)

        if not path.is_relative_to(outdir):
            raise ValueError(f'{err_msg_prefix}: path `{items[0]}` is outside of output directory `{outdir}`')

        entries.append([path, target])

    config.doxygen_links = entries


def on_builder_inited(app):
    # Remove the symlinks if they exist, to avoid overwriting the index.html
    # generated by Doxygen with the placeholder index from Sphinx.

    for path, target in app.config.doxygen_links:
        if path.is_symlink():
            logger.info(f'Removing existing symlink {path}')
            os.unlink(path)


def on_build_finished(app, exc):
    # Create the symlinks. Remove any existing placeholder directory
    # recursively first.

    if exc:
        return

    for path, target in app.config.doxygen_links:
        logger.info(f'Creating symlink {path} -> {target}')

        if path.is_dir():
            shutil.rmtree(path)

        os.symlink(target, path)


def setup(app):
    app.add_config_value('doxygen_links', [], 'env', frozenset({list, tuple}))
    app.connect('config-inited', on_config_inited)
    app.connect('builder-inited', on_builder_inited)
    app.connect('build-finished', on_build_finished)

    return {
        "version": __version__,
        "parallel_read_safe": True,
        "parallel_write_safe": True,
    }
